shell = /bin/zsh
env TERM = xterm-256color
env EDITOR = vim

color_fg = 220,220,220
color_bg = 0,0,0
border_color = 100,100,100

bind ctrl+v = split_vert
bind ctrl+b = split_horz
bind ctrl+w = close_pane
bind alt+left = resize_left